### ISSUE TITLE
Datapackage.Json Creator: no output nor error message

### ISSUE THREAD

**Issue by greggish** [okfn/data.okfn.org#217]
I've tried to upload a set of CSV files to [the Datapackage.Json creator](http://data.okfn.org/tools/create), but received no output. I very well may have done something wrong, but I also received no error message. 

(Perhaps it a problem with my CSV files? However, @practicalparticipation also seemed to have trouble... unlike me, he actually knows what he's doing.)

Any help appreciated :)

**Comment by danfowler** [comment]
Hi @greggish sorry to hear that.  We're in the process of heavily refactoring data.okfn.org.  

Can you try our more up-to-date tool for creating Data Packages: http://datapackagist.okfnlabs.org/

**Comment by danfowler** [comment]
Also, @greggish feel free to hop onto http://gitter.im/frictionlessdata/chat to talk about how you're using Data Packages :)

**Comment by rgrp** [comment]
@greggish first, thanks for flagging the bug. It turns out that a change in datapackage-init-js broke this creator: https://github.com/okfn/datapackage-init-js/issues/21

Anyway, as @danfowler says we have a much nicer data package creator at:

http://datapackagist.okfnlabs.org/

I'm just about to update data.okfn.org/tools/create to redirect to that!

**Comment by greggish** [comment]
Thanks, folks!
